### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by Tibolte** [pwittchen/WeatherIconView#1]
I like the idea of this project. I want to use it and I'm wondering if can import it to my project by a Gradle dependency? I don't recall seeing that described.

**Comment by pwittchen** [comment]
Currently it's not deployed into Maven Central. I see, there are users, who would like to use it, so I'll deploy it to Maven Central in my free time. In the meantime, you can just clone this project and use it as library dependency.

**Comment by Tibolte** [comment]
Thanks I appreciate it. Keep up the work!

**Comment by jitpack-io** [comment]
@Tibolte @pwittchen Perhaps this will help in the meantime: https://jitpack.io/#pwittchen/WeatherIconView/1919f553fd

**Comment by pwittchen** [comment]
@jitpack-io Thanks! I know your service and it's very useful. I need to check out more details.

**Comment by jitpack-io** [comment]
@pwittchen Great! A quick win would be to add a GitHub release https://github.com/pwittchen/WeatherIconView/releases so that there is a version number.

**Comment by Tibolte** [comment]
@jitpack-io great idea!!

**Comment by pwittchen** [comment]
I've uploaded archives to Maven Central Repository. Now, we need to wait for the Maven Sync. If everything will be ok, I'll test it and add download section to README.md file and create GitHub release.

**Comment by Tibolte** [comment]
:+1:

**Comment by pwittchen** [comment]
Ok. Maven Sync is done. I've tested this as Gradle dependency in a test project and it works fine.
First release is available here: https://github.com/pwittchen/WeatherIconView/releases/tag/v1.0.0
Download section can be found here: https://github.com/pwittchen/WeatherIconView#download

Happy coding!

**Comment by Tibolte** [comment]
Thanks @pwittchen !

**Comment by pwittchen** [comment]
You're welcome.
