### ISSUE TITLE
Icon size changing.

### ISSUE THREAD

**Issue by Silverpp** [pwittchen/WeatherIconView#10]
Thanks for sharing your brilliant code.

Changing font size in the Android's display settings also changes weather icon size.
Is there any way to solve this problem?

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting the issue. Does this problem occur when you are setting icon size via `weatherIconView.setIconSize(int)` method or via XML?

**Comment by Silverpp** [comment]
Thanks for quick reply.
I tried both way but results are same.

**Comment by pwittchen** [comment]
Basically weather icons provided by this library are fonts under the hood, so if someone explicitly changes font size in the settings of the whole Android system, I'm not sure if it's possible to change this behaviour via the application code.

**Comment by Silverpp** [comment]
I didn't know WeatherIconView class just extents TextView :)

So I'm solved my problem in easy way.
mYahooWeatherIcon.setTextSize(TypedValue.COMPLEX_UNIT_DIP, CURRENT_ICON_SIZE_IN_DP);
//        mYahooWeatherIcon.setIconSize(CURRENT_ICON_SIZE_IN_DP);

Thank you!!!

**Comment by pwittchen** [comment]
Great!
