### ISSUE TITLE
Colorful Weather Icons

### ISSUE THREAD

**Issue by rnayabed** [pwittchen/WeatherIconView#12]
Thanks for making such a useful library. 
Wouldn't it be better if we had colorful icons rather than a particular icon?
Expecting a quick reply...

**Comment by pwittchen** [comment]
Hi,

You can set color of the icon via XML like that:

```xml
<com.github.pwittchen.weathericonview.WeatherIconView
    android:id="@+id/my_weather_icon"
    custom:weatherIconColor="@android:color/black" />
```

or in Java:

```java
WeatherIconView weatherIconView;
weatherIconView = (WeatherIconView) findViewById(R.id.my_weather_icon);
weatherIconView.setIconColor(Color.BLACK);
```

In this case colors are monochromatic. Library is based on a `*.ttf` font, so it's not possible to have multiple colors on icon with this approach. If you would like to have something like that, then you need to add regular images to your app.
