### ISSUE TITLE
Missing icons from version 2.0? (question)

### ISSUE THREAD

**Issue by Dzoukr** [pwittchen/WeatherIconView#3]
I really love this library, great work! Please, do you plan to add newly added icons from version 2.0? I mean those mentioned on https://erikflowers.github.io/weather-icons/ as "25 New 2.0 Icons!" Thanks for reply.

**Comment by pwittchen** [comment]
Thanks for informing about new set of icons. I'll check this out and update library if they won't be any problems with the new set. In addition, I'll have to review icon codes, add new codes and update existing codes if necessary.

**Comment by Dzoukr** [comment]
Very thanks for your effort!

**Comment by nibuen** [comment]
@pwittchen Looks like someone has made a pull request for the 2.0 android assets file here: https://github.com/erikflowers/weather-icons/pull/109

**Comment by pwittchen** [comment]
@nibuen Thanks! It helps me a lot! I didn't have time to take a closer look on the 2.0 version yet. I'll check this out, test it and update font and resources as soon as possible.

**Comment by pwittchen** [comment]
Related PR: #5.

**Comment by pwittchen** [comment]
Done.

**Comment by pwittchen** [comment]
Thanks goes to @nibuen for his Pull Request!
