### ISSUE TITLE
adding icons from a java file

### ISSUE THREAD

**Issue by mpayancabrera** [pwittchen/WeatherIconView#9]
Hello,
first, congratulations for your work. 

The problem is that when I try to add an icon from a java file it is wrong. The sentence
"weatherIconView.setIconResource(getString(R.string.wi_day_snow));" fail when the method getString is called.
Error:(114, 45) error: cannot find symbol method getString(int)
What else  I need to add to make it works?

Thanks in advance,
Manuel

**Comment by pwittchen** [comment]
I don't know your code, but a method named `getString(...)` is the part of the `Context` class. `Activity` and `Application` classes derive from it. You need to be in the scope of Context (e.g. `Activity`) to call `getString(...)`.

Reference: https://developer.android.com/reference/android/content/Context.html#getString(int)

**Comment by mpayancabrera** [comment]
Thanks for your early reply. That was the issue, now it works properly. 
I have a ListView and I insert the icon from the getView method of the adapter but out of context.

Thanks so much again. 👍

**Comment by pwittchen** [comment]
Great, you fixed this! :+1: 

In the case of more problems don't hesitate to create another issue. I think this one can be closed now.

Regards,
Piotr
